# ============================================================
#  Project    : Tigers & Goats – Falcon Branch
#  Module     : Experiment Sweep Runner (Training + Variations)
#  File       : train_falcon.py
#  Version    : mppo_train3.0
#  Last Update: 2026-01-03
#
#  What this file does:
#    Runs an *experiment suite* made of multiple *variations*, where each
#    variation can be either:
#      (A) A single baseline run (reward_weights=None)
#      (B) A single-phase override dict (weights/knobs + optional phase settings)
#      (C) A multi-phase curriculum (list of phases) that continues training
#          the *same* model across phases (new TB subdir per phase).
#
#    Each phase creates a fresh SubprocVecEnv, trains for phase_steps, logs
#    windowed outcome metrics, saves periodic checkpoints, then closes the env.
#
#  Key concepts:
#    • EXPERIMENT_NAME / SUITE_TAG:
#         Suite name. Logs + models are grouped under this.
#
#    • CORE (matchup tag):
#         Generated by core_tag(learner_role, tiger_ai, mix=USE_MIX_TAG)
#           - GvNT: Goat vs Normal/Greedy Tiger
#           - GvST: Goat vs Smart Tiger
#           - GvMixT: Goat vs Mixed Tiger (per-reset sampling)
#           - Tv...: Tiger-learner versions (goats become scripted opponent)
#
#    • VARIATIONS:
#         variation_name -> config, where config can be:
#           (A) None
#               → env defaults
#           (B) dict
#               → one phase; supports optional inline keys:
#                   {"timesteps", "tiger_ai", "mix_prob", "checkpoints_per_run", ...weights...}
#           (C) list[dict]
#               → multi-phase curriculum:
#                   [{"timesteps": ..., "tiger_ai": ..., "mix_prob": ..., "reward_weights": ...}, ...]
#
#    • Tiger mixing (per-reset opponent sampling):
#         If mix_prob is set in a phase, each episode reset samples:
#            TIGER_AI_SMART with probability mix_prob
#            TIGER_AI_GREEDY otherwise
#         Implemented via TigerMixWrapper (Monitor subclass) so it remains
#         pickle-friendly under SubprocVecEnv.
#
#    • Action masking (MaskablePPO requirement):
#         Each worker env is wrapped:
#           BaseEnv -> (Monitor or TigerMixWrapper) -> ActionMasker
#         so MaskablePPO only samples legal actions.
#
#  Outputs (where stuff goes):
#    • TensorBoard logs (one subdir per variation phase):
#         artifacts/logging/train/{ALGO_TAG}/{CORE}/{SUITE_TAG}/
#           └── {ALGO_TAG}_{CORE}_{variation_name}_p{phase_idx}/
#
#    • Models + checkpoints:
#         artifacts/models/train/{ALGO_TAG}/{CORE}/{SUITE_TAG}/
#           ├── cp_{ALGO_TAG}_{CORE}_{variation_name}_...  (checkpoints)
#           └── {ALGO_TAG}_{CORE}_{variation_name}_p{last_phase}.zip (final model)
#
#    • Resume support:
#         RESUME_MODEL_PATH can be a .zip file OR a directory.
#         If directory, the most recently created .zip is loaded and training
#         continues from it (phase 0 treated as "continued").
#
#  Metrics you should expect in TensorBoard:
#    • 1.episode_stats/*
#         - episode_index
#         - episodes_total_done
#         - overall goat/tiger/timeout/stall rates (cumulative)
#
#    • 2.window_stats/*
#         - windowed goat/tiger/timeout/stall rates over last N episodes
#         - realized opponent fraction (greedy vs smart) in the last N episodes
#           when tiger mode is mixed
#
#    • 3.matchup_info/*
#         - learner_id (0=goat, 1=tiger)
#         - opp_source_id (0=tiger, 1=goat)
#         - opp_family_id (0=greedy/random, 1=smart/model)
#         - is_mixed (0/1)
#         - mix_prob (if mixed)
#
#  Quick Use:
#    1) Choose opponent + role:
#         TIGER_AI_MODE = TIGER_AI_GREEDY   # “normal/greedy”
#         # or
#         TIGER_AI_MODE = TIGER_AI_SMART    # “smart”
#         LEARNER_ROLE  = GOAT_LEARNER      # or TIGER_LEARNER
#
#    2) Set identity + compute:
#         EXPERIMENT_NAME = "RobustGoatTraining"
#         TIMESTEPS       = 60_000_000
#         NUM_CPU         = 16
#         DEVICE_MODE     = "gpu"  # uses cuda + larger batch/n_steps
#
#    3) Define variations:
#         VARIATIONS = {
#             "defaultSettings": None,
#             "no_bubble": {"bubble": 0.0},
#             "no_block": {"block_tiger": 0.0},
#             "weaker_capture_bias": {"BASE_TIGER_CAPTURE_BIAS": 0.8},
#         }
#
#       Curriculum + mixing example:
#         VARIATIONS = {
#           "greedy_to_smart_mix": [
#             {"timesteps": 10_000_000, "tiger_ai": TIGER_AI_GREEDY, "reward_weights": None},
#             {"timesteps": 10_000_000, "tiger_ai": TIGER_AI_SMART,  "reward_weights": None},
#             {"timesteps": 30_000_000, "tiger_ai": TIGER_AI_SMART,  "mix_prob": 0.3, "reward_weights": None},
#             {"timesteps": 30_000_000, "tiger_ai": TIGER_AI_SMART,  "mix_prob": 0.5, "reward_weights": None},
#           ]
#         }
#
#    4) Run:
#         python train_falcon.py
#
#    5) Watch training:
#         tensorboard --logdir artifacts/logging/train --port 6006
#
#  Workflow (recommended for ablation studies):
#    1) Establish baseline (single variation, defaults).
#    2) One-at-a-time ablations (set one weight to 0.0).
#    3) Group ablations (remove shaping families).
#    4) Magnitude sweeps (0.0, 0.25, 0.5, 1.0, 2.0).
#    5) Curriculum runs (greedy -> smart, optional mixing for robustness).
#    6) Evaluate winners with eval_falcon.py across fixed episode counts.
#
# ============================================================



import os
import numpy as np
import torch
import glob
from collections import deque
import random
import sys

from stable_baselines3.common.vec_env import SubprocVecEnv
from stable_baselines3.common.utils import set_random_seed
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.callbacks import (
    CheckpointCallback,
    BaseCallback,
    CallbackList,
)
from stable_baselines3.common.logger import configure
from sb3_contrib import MaskablePPO
from sb3_contrib.common.wrappers import ActionMasker

from env_tng_abc import (
    TnGEnv as BaseEnv,
    TIGER_AI_GREEDY,
    TIGER_AI_SMART,
    GOAT_AI_RANDOM,
    GOAT_AI_MODEL,
)

GOAT_LEARNER     = "goat"
TIGER_LEARNER    = "tiger"
OPP_TIGER_GREEDY = "tiger_greedy"
OPP_TIGER_SMART  = "tiger_smart"
OPP_TIGER_MODEL  = "tiger_model"   # reserved; env_tng_falcon does not yet support model tigers
OPP_GOAT_RANDOM  = "goat_random"
OPP_GOAT_MODEL   = "goat_model"

# ============================================================
#  USER CONFIG — Opponent & Naming
# ============================================================

EXPERIMENT_NAME = "BenchmarkTigerTraining"
LEARNER_ROLE    = TIGER_LEARNER                # GOAT_LEARNER | TIGER_LEARNER
# Unified opponent selector (interpreted by learner role; used when MIX_PROB is None):
#   - GOAT learner  : "tiger_greedy" | "tiger_smart"  (model tiger not yet supported)
#   - TIGER learner : "goat_random"  | "goat_model"
OPPONENT_AI     = OPP_GOAT_RANDOM
# Mixing control (set to None for fixed opponent):
#   - GOAT learner  : P(smart tiger), else greedy
#   - TIGER learner : P(model goat),  else random
MIX_PROB        = None

ALGO_TAG        = "mppo"
ENV_VER         = "env_5.0"
MODEL_VER       = "mppo_train3.0"
CHECKPOINTS_PER_RUN = 10
RESUME_MODEL_PATH = None
GOAT_MODEL_PATH  = None  # path to a saved goat model (used when opponent is goat_model)

USE_MIX_TAG     = MIX_PROB is not None  # adds "Mix" to CORE tag (tag only)

# ============================================================
#  USER CONFIG — Scale / Hardware
# ============================================================

DEVICE_MODE = "cpu"
DEBUG_MODE  = False                  # True or False
TIMESTEPS   = 2_000_000 if DEBUG_MODE else 100_000_000
NUM_CPU     = 16
SEED        = 42

# ============================================================
#  USER CONFIG — PPO Hyperparameters
# ============================================================

GAMMA         = 0.99
LEARNING_RATE = 3e-4
ENT_COEF      = 0.02

if DEVICE_MODE == "gpu":
    DEVICE     = "cuda"
    N_STEPS    = 4096
    BATCH_SIZE = 256
    N_EPOCHS   = 10
    torch.set_num_threads(1)
elif DEVICE_MODE == "cpu":
    DEVICE     = "cpu"
    N_STEPS    = 512
    BATCH_SIZE = 128
    N_EPOCHS   = 5
else:
    raise ValueError("DEVICE_MODE must be 'gpu' or 'cpu'")

# ============================================================
#  VARIATIONS
# ============================================================

VARIATIONS = {
    "tiger_vs_random_goat_100M": [
        {"timesteps": 10_000_000, "opponent_ai": OPP_GOAT_RANDOM, "mix_prob": None},
    ]
}


# ============================================================
# Helpers
# ============================================================

def core_tag(
    learner_role: str,
    opponent_ai: str,
    mix: bool = False,
    goat_opponent_ai: str | None = None,
) -> str:
    """
    Build a matchup tag:
      - GOAT learner: opponent_ai refers to tiger mode (greedy/smart), mix uses generic MixT.
      - TIGER learner: opponent_ai/goat_opponent_ai refers to goat type (random/model),
        mix marks a mixed-goat opponent.
    """
    learner = "G" if learner_role == GOAT_LEARNER else "T"
    if learner == "T":
        goat_ai = goat_opponent_ai or opponent_ai
        if mix:
            opp = "MixG"
        else:
            opp = "MG" if goat_ai == GOAT_AI_MODEL else "RG"
    else:
        base_opp = "NT" if opponent_ai == TIGER_AI_GREEDY else "ST"
        opp = "MixT" if mix else base_opp
    return f"{learner}v{opp}"


def resolve_opponent_or_exit(learner_role: str, opponent_ai: str) -> tuple[str, str]:
    """
    Map a unified opponent string to (tiger_ai_mode, goat_opponent_ai),
    exiting if the combination is invalid for the current learner role.
    """
    lr = learner_role.lower()
    opp = opponent_ai.lower()

    if lr == GOAT_LEARNER:
        if opp == OPP_TIGER_GREEDY:
            return TIGER_AI_GREEDY, GOAT_AI_RANDOM
        if opp == OPP_TIGER_SMART:
            return TIGER_AI_SMART, GOAT_AI_RANDOM
        print("GOAT learner requires OPPONENT_AI in {tiger_greedy, tiger_smart}")
        sys.exit(1)

    if lr == TIGER_LEARNER:
        if opp == OPP_GOAT_RANDOM:
            return TIGER_AI_SMART, GOAT_AI_RANDOM
        if opp == OPP_GOAT_MODEL:
            return TIGER_AI_SMART, GOAT_AI_MODEL
        print("TIGER learner requires OPPONENT_AI in {goat_random, goat_model}")
        sys.exit(1)

    print("learner_role must be GOAT_LEARNER or TIGER_LEARNER")
    sys.exit(1)


def normalize_phases(reward_weights) -> list[dict]:
    if isinstance(reward_weights, list):
        return reward_weights
    if isinstance(reward_weights, dict):
        # Single-phase dict: allow inline timesteps/opponent_ai/mix_prob/checkpoints_per_run
        phase_timesteps = reward_weights.get("timesteps", TIMESTEPS)
        phase_checkpoints = reward_weights.get("checkpoints_per_run", CHECKPOINTS_PER_RUN)
        phase_opponent = reward_weights.get("opponent_ai", reward_weights.get("tiger_ai", OPPONENT_AI))
        phase_mix = reward_weights.get("mix_prob", MIX_PROB)
        phase_goat_model = reward_weights.get("goat_model_path", GOAT_MODEL_PATH)
        phase_rewards = {
            k: v for k, v in reward_weights.items()
            if k not in {"timesteps", "tiger_ai", "opponent_ai", "mix_prob", "checkpoints_per_run", "goat_model_path"}
        } or None
        return [{
            "timesteps": phase_timesteps,
            "opponent_ai": phase_opponent,
            "mix_prob": phase_mix,
            "goat_model_path": phase_goat_model,
            "checkpoints_per_run": phase_checkpoints,
            "reward_weights": phase_rewards,
        }]
    return [{
        "timesteps": TIMESTEPS,
        "opponent_ai": OPPONENT_AI,
        "mix_prob": MIX_PROB,
        "goat_model_path": GOAT_MODEL_PATH,
        "reward_weights": reward_weights,
        "checkpoints_per_run": CHECKPOINTS_PER_RUN,
    }]


def resolve_variation_core(phases: list[dict]) -> str:
    phase_list = phases if phases else [{"opponent_ai": OPPONENT_AI, "mix_prob": MIX_PROB}]
    is_mixed = any(phase.get("mix_prob", MIX_PROB) is not None for phase in phase_list)

    tiger_modes = set()
    goat_modes = set()
    for phase in phase_list:
        phase_opponent = phase.get("opponent_ai", phase.get("tiger_ai", OPPONENT_AI))
        tiger_ai, goat_opp = resolve_opponent_or_exit(LEARNER_ROLE, phase_opponent)
        tiger_modes.add(tiger_ai)
        goat_modes.add(goat_opp)

    if LEARNER_ROLE == GOAT_LEARNER:
        if is_mixed:
            sample_tiger = next(iter(tiger_modes), TIGER_AI_GREEDY)
            return core_tag(LEARNER_ROLE, sample_tiger, mix=True, goat_opponent_ai=GOAT_AI_RANDOM)
        if len(tiger_modes) == 1:
            only_tiger = next(iter(tiger_modes))
            return core_tag(LEARNER_ROLE, only_tiger, mix=False, goat_opponent_ai=GOAT_AI_RANDOM)
        return "GvNTST"

    if is_mixed:
        sample_goat = next(iter(goat_modes), GOAT_AI_RANDOM)
        return core_tag(LEARNER_ROLE, TIGER_AI_SMART, mix=True, goat_opponent_ai=sample_goat)
    if len(goat_modes) == 1:
        only_goat = next(iter(goat_modes))
        return core_tag(LEARNER_ROLE, TIGER_AI_SMART, mix=False, goat_opponent_ai=only_goat)
    return "TvRGMG"


def make_goat_model_predict_fn(model_path: str | None):
    if not model_path:
        return None

    model = None

    def _predict(obs, mask):
        nonlocal model
        if model is None:
            model = MaskablePPO.load(model_path, device=DEVICE)
        obs_arr = np.asarray(obs)
        if obs_arr.ndim == 1:
            obs_arr = obs_arr.reshape(1, -1)
        mask_arr = None
        if mask is not None:
            mask_arr = np.asarray(mask, dtype=bool)
            if mask_arr.ndim == 1:
                mask_arr = mask_arr.reshape(1, -1)
        action, _ = model.predict(obs_arr, deterministic=True, action_masks=mask_arr)
        if isinstance(action, np.ndarray):
            return int(action[0])
        return int(action)

    return _predict


def warn_if_missing_goat_model_path(goat_opponent_ai: str, model_path: str | None, context: str):
    if goat_opponent_ai == GOAT_AI_MODEL and not model_path:
        print(f"[WARN] {context}: opponent_ai=goat_model but goat_model_path is not set; falling back to random goat.")


def mask_fn(env):
    return env.unwrapped.get_action_mask()

def tiger_code(tiger_ai: str) -> int:
    return 1 if tiger_ai == TIGER_AI_SMART else 0

def tb_add_text(model_obj, tag: str, text: str, step: int):
    """
    Optional: add Text to TensorBoard if a TB writer exists.
    Safe no-op if not.
    """
    try:
        for fmt in model_obj.logger.output_formats:
            w = getattr(fmt, "writer", None)
            if w is not None:
                w.add_text(tag, text, step)
                break
    except Exception:
        pass

# ============================================================
# Derived config (auto from user settings)
# ============================================================

# Resolve default opponent for suite tag/logging
TIGER_AI_MODE, GOAT_OPPONENT_AI = resolve_opponent_or_exit(LEARNER_ROLE, OPPONENT_AI)
CORE      = core_tag(LEARNER_ROLE, TIGER_AI_MODE, mix=USE_MIX_TAG, goat_opponent_ai=GOAT_OPPONENT_AI)
SUITE_TAG = EXPERIMENT_NAME

LOG_DIR   = f"artifacts/logging/train/{ALGO_TAG}/{CORE}/{SUITE_TAG}"
MODEL_DIR = f"artifacts/models/train/{ALGO_TAG}/{CORE}/{SUITE_TAG}"

CHECKPOINT_INTERNAL_STEPS = TIMESTEPS // CHECKPOINTS_PER_RUN
SAVE_FREQ = max(CHECKPOINT_INTERNAL_STEPS // NUM_CPU, 1)

os.makedirs(LOG_DIR, exist_ok=True)
os.makedirs(MODEL_DIR, exist_ok=True)

# ============================================================
# Callbacks
# ============================================================

class EpisodeCounterCallback(BaseCallback):
    def __init__(self):
        super().__init__()
        self.episode_count = 0

    def _on_step(self):
        dones = self.locals.get("dones", None)
        if dones is not None:
            self.episode_count += int(np.sum(dones))
        self.logger.record("1.episode_stats/2.episodes_total_done", float(self.episode_count))
        return True

class WinStatsCallback(BaseCallback):
    """
    Windowed win/timeout stats + optional realized tiger-mode tracking.
    If env includes info["tiger_ai"] at episode end, we will track it.
    """
    def __init__(self, log_every_episodes: int = 200, window_episodes: int = 1_000, verbose: int = 0):
        super().__init__(verbose)
        self.log_every_episodes = log_every_episodes
        self.last_logged_episodes = 0

        # cumulative
        self.episodes = 0
        self.goat_wins = 0
        self.tiger_wins = 0
        self.max_timeouts = 0
        self.repeat_timeouts = 0

        # rolling window of winners
        self.window = deque(maxlen=window_episodes)

        # rolling window of realized opponent modes (optional)
        self.window_tiger_ai = deque(maxlen=window_episodes)  # values: greedy/smart/None
        self.window_goat_ai = deque(maxlen=window_episodes)   # values: random/model/None

    def _on_step(self) -> bool:
        dones = self.locals.get("dones", None)
        infos = self.locals.get("infos", None)

        if dones is not None and infos is not None:
            for done, info in zip(dones, infos):
                if not done:
                    continue

                winner = info.get("winner", None)

                self.episodes += 1
                if winner == "Goat":
                    self.goat_wins += 1
                elif winner == "Tiger":
                    self.tiger_wins += 1
                elif winner == "MaxTimeout":
                    self.max_timeouts += 1
                elif winner == "RepeatTimeout":
                    self.repeat_timeouts += 1

                self.window.append(winner)

                # optional: realized opponent mode
                # env_tng_falcon can set info["tiger_ai"] = TIGER_AI_GREEDY/SMART (or strings)
                self.window_tiger_ai.append(info.get("tiger_ai", None))
                self.window_goat_ai.append(info.get("goat_opponent_ai", info.get("goat_ai", None)))

        # always keep current episode index in logs
        self.logger.record("1.episode_stats/1.episode_index", float(self.episodes))

        if (self.episodes - self.last_logged_episodes) >= self.log_every_episodes and self.episodes > 0:
            total = float(self.episodes)

            self.last_logged_episodes = self.episodes
            # Order of logs (to control TB display grouping)
            self.logger.record("1.episode_stats/3.episodes_total_winstats", total)
            self.logger.record("1.episode_stats/4.goat_win_rate", self.goat_wins / total)
            self.logger.record("1.episode_stats/5.tiger_win_rate", self.tiger_wins / total)
            self.logger.record("1.episode_stats/6.max_timeout_rate", self.max_timeouts / total)
            self.logger.record("1.episode_stats/7.repeat_timeout_rate", self.repeat_timeouts / total)

            w = len(self.window)
            if w > 0:
                goat = sum(1 for x in self.window if x == "Goat") / w
                tiger = sum(1 for x in self.window if x == "Tiger") / w
                to = sum(1 for x in self.window if x == "MaxTimeout") / w
                st = sum(1 for x in self.window if x == "RepeatTimeout") / w

                self.logger.record("2.window_stats/1.episodes_tracked", float(w))
                self.logger.record("2.window_stats/2.goat_win_rate", goat)
                self.logger.record("2.window_stats/3.tiger_win_rate", tiger)
                self.logger.record("2.window_stats/4.max_timeout_rate", to)
                self.logger.record("2.window_stats/5.repeat_timeout_rate", st)

                # optional realized opponent distribution in the last-N window
                smart = 0
                greedy = 0
                for v in self.window_tiger_ai:
                    if v == TIGER_AI_SMART or v == "smart" or v == "SMART":
                        smart += 1
                    elif v == TIGER_AI_GREEDY or v == "greedy" or v == "GREEDY":
                        greedy += 1
                denom = smart + greedy
                if denom > 0:
                    self.logger.record("2.window_stats/6.realized_greedy_tiger_frac", greedy / denom)
                    self.logger.record("2.window_stats/7.realized_smart_tiger_frac", smart / denom)

                model = 0
                random_goat = 0
                for v in self.window_goat_ai:
                    if v == GOAT_AI_MODEL or v == "model" or v == "MODEL":
                        model += 1
                    elif v == GOAT_AI_RANDOM or v == "random" or v == "RANDOM":
                        random_goat += 1
                denom = model + random_goat
                if denom > 0:
                    self.logger.record("2.window_stats/8.realized_random_goat_frac", random_goat / denom)
                    self.logger.record("2.window_stats/9.realized_model_goat_frac", model / denom)

        return True
    

class TigerMixWrapper(Monitor):
    """
    Monitor wrapper that re-samples tiger_ai on every reset using a callable.
    Keeps it top-level (pickle-friendly) and avoids nested class definitions.
    """
    def __init__(self, env, sample_ai_fn):
        super().__init__(env)
        self._sample_ai_fn = sample_ai_fn

    def reset(self, *, seed=None, options=None):
        # Make sure we are modifying the underlying env that actually owns tiger_ai
        ai = self._sample_ai_fn()
        try:
            self.env.tiger_ai = ai
        except Exception:
            pass
        return super().reset(seed=seed, options=options)


class GoatMixWrapper(Monitor):
    """
    Monitor wrapper that re-samples goat_opponent_ai on every reset using a callable.
    Used when the learner is TIGER and we want to mix random/model goats.
    """
    def __init__(self, env, sample_goat_fn):
        super().__init__(env)
        self._sample_goat_fn = sample_goat_fn

    def reset(self, *, seed=None, options=None):
        goat_ai = self._sample_goat_fn()
        # Propagate to underlying env
        try:
            self.env.goat_opponent_ai = goat_ai
        except Exception:
            pass
        return super().reset(seed=seed, options=options)


# ============================================================
# Env factory (supports per-reset mixing)
# ============================================================

def make_env(
    rank: int,
    seed: int,
    reward_weights,
    tiger_ai=None,
    mix_prob=None,
    goat_opponent_ai=None,
    goat_model_path=None,
):
    def _init():
        def _sample_ai():
            if mix_prob is None:
                return tiger_ai if tiger_ai is not None else TIGER_AI_MODE
            p = min(max(float(mix_prob), 0.0), 1.0)
            return TIGER_AI_SMART if random.random() < p else TIGER_AI_GREEDY

        def _sample_goat_ai():
            base_goat = goat_opponent_ai if goat_opponent_ai is not None else GOAT_OPPONENT_AI
            if mix_prob is None or LEARNER_ROLE == GOAT_LEARNER:
                return base_goat
            p = min(max(float(mix_prob), 0.0), 1.0)
            return GOAT_AI_MODEL if random.random() < p else GOAT_AI_RANDOM

        goat_model_predict_fn = make_goat_model_predict_fn(goat_model_path)
        base_env = BaseEnv(
            reward_weights=reward_weights,
            tiger_ai=_sample_ai(),
            learner_role=LEARNER_ROLE,
            goat_opponent_ai=_sample_goat_ai(),
            goat_model_predict_fn=goat_model_predict_fn,
        )

        # If mixing, resample per reset
        if mix_prob is not None and LEARNER_ROLE == GOAT_LEARNER:
            env = TigerMixWrapper(base_env, _sample_ai)
        elif mix_prob is not None and LEARNER_ROLE == TIGER_LEARNER:
            env = GoatMixWrapper(base_env, _sample_goat_ai)
        else:
            env = Monitor(base_env)

        env = ActionMasker(env, mask_fn)
        env.reset(seed=seed + rank)
        return env
    return _init

# ============================================================
# Resume helpers
# ============================================================

def resolve_resume_path(path: str | None) -> str | None:
    if not path:
        return None
    if os.path.isfile(path):
        return path
    if os.path.isdir(path):
        zips = glob.glob(os.path.join(path, "*.zip"))
        if not zips:
            return None
        return max(zips, key=os.path.getctime)
    return None

def unique_filename(directory: str, base_name: str, ext: str = ".zip") -> str:
    full_path = os.path.join(directory, base_name + ext)
    if not os.path.exists(full_path):
        return full_path
    counter = 1
    while True:
        candidate = os.path.join(directory, f"{base_name}_{counter}{ext}")
        if not os.path.exists(candidate):
            return candidate
        counter += 1

# ============================================================
# Matchup info logger (scalar)
# ============================================================

def log_matchup_info(model_obj, learner_role, tiger_ai, goat_opponent_ai, mix_prob):
    learner_id = 0.0 if learner_role == GOAT_LEARNER else 1.0
    opp_source_id = 0.0 if learner_role == GOAT_LEARNER else 1.0  # 0=tiger, 1=goat
    if learner_role == GOAT_LEARNER:
        opp_family_id = 1.0 if tiger_ai == TIGER_AI_SMART else 0.0
    else:
        opp_family_id = 1.0 if goat_opponent_ai == GOAT_AI_MODEL else 0.0

    model_obj.logger.record("3.matchup_info/1.learner_id", learner_id)
    model_obj.logger.record("3.matchup_info/2.opp_source_id", opp_source_id)
    model_obj.logger.record("3.matchup_info/3.opp_family_id", opp_family_id)
    model_obj.logger.record("3.matchup_info/4.is_mixed", 0.0 if mix_prob is None else 1.0)
    if mix_prob is not None:
        model_obj.logger.record("3.matchup_info/5.mix_prob", float(mix_prob))
    model_obj.logger.dump(step=model_obj.num_timesteps)

# ============================================================
# Core: run one variation
# ============================================================

def run_single_variation(variation_name: str, reward_weights):
    set_random_seed(SEED)

    phases = normalize_phases(reward_weights)

    variation_core = resolve_variation_core(phases)
    variation_log_dir = f"artifacts/logging/train/{ALGO_TAG}/{variation_core}/{SUITE_TAG}"
    variation_model_dir = f"artifacts/models/train/{ALGO_TAG}/{variation_core}/{SUITE_TAG}"
    os.makedirs(variation_log_dir, exist_ok=True)
    os.makedirs(variation_model_dir, exist_ok=True)

    print(f"Starting {NUM_CPU} env workers ({variation_core})...")
    print(f"ENV_VER={ENV_VER}, MODEL_VER={MODEL_VER}, TIMESTEPS={TIMESTEPS}")
    print(f"DEVICE_MODE={DEVICE_MODE}, DEVICE={DEVICE}")
    print("=" * 70)
    print(f"Starting variation: {variation_name}")
    print("=" * 70)

    tb_subdir = f"{ALGO_TAG}_{variation_core}_{variation_name}"

    policy_kwargs = dict(net_arch=[256, 256, 256])

    resume_path = resolve_resume_path(RESUME_MODEL_PATH)
    if RESUME_MODEL_PATH and not resume_path:
        print(f"[{variation_name}] [WARN] RESUME_MODEL_PATH set but no .zip found at: {RESUME_MODEL_PATH}")
    resumed = bool(resume_path)

    model = None
    model_identity = None

    total_goat = total_tiger = total_to = total_st = 0
    total_eps = 0

    for phase_idx, phase in enumerate(phases):
        phase_steps = phase.get("timesteps", TIMESTEPS)
        phase_rewards = phase.get("reward_weights", None)
        phase_opponent = phase.get("opponent_ai", phase.get("tiger_ai", OPPONENT_AI))
        phase_mix = phase.get("mix_prob", MIX_PROB)
        phase_goat_model = phase.get("goat_model_path", GOAT_MODEL_PATH)
        phase_cpr = phase.get("checkpoints_per_run", CHECKPOINTS_PER_RUN)
        phase_save_freq = max((phase_steps // max(phase_cpr, 1)) // NUM_CPU, 1)

        phase_tiger_ai, phase_goat_opp = resolve_opponent_or_exit(LEARNER_ROLE, phase_opponent)
        phase_mix_env = phase_mix

        print(f"Phase {phase_idx}: timesteps={phase_steps}, opponent_ai={phase_opponent}, mix_prob={phase_mix_env}")
        warn_if_missing_goat_model_path(
            phase_goat_opp,
            phase_goat_model,
            context=f"variation={variation_name} phase={phase_idx}",
        )

        env_fns = [
            make_env(
                i,
                seed=SEED,
                reward_weights=phase_rewards,
                tiger_ai=phase_tiger_ai,
                mix_prob=phase_mix_env,
                goat_opponent_ai=phase_goat_opp,
                goat_model_path=phase_goat_model,
            )
            for i in range(NUM_CPU)
        ]
        vec_env = SubprocVecEnv(env_fns)

        win_stats_callback = WinStatsCallback()
        ep_callback = EpisodeCounterCallback()

        chk_callback = CheckpointCallback(
            save_freq=phase_save_freq,
            save_path=variation_model_dir,
            name_prefix=f"cp_{ALGO_TAG}_{variation_core}_{variation_name}",
            save_replay_buffer=True,
            save_vecnormalize=True,
        )

        callback = CallbackList([
            chk_callback, 
            ep_callback, 
            win_stats_callback
            ]
        )

        phase_tb = f"{tb_subdir}_p{phase_idx}"
        log_path = os.path.join(variation_log_dir, phase_tb)

        if model is None:
            if resume_path:
                print(f"[{variation_name}] Loading existing model for continued training:\n  {resume_path}")
                model = MaskablePPO.load(resume_path, env=vec_env, device=DEVICE)
                model.set_env(vec_env)
                model.verbose = 1
                model.set_logger(configure(log_path, ["tensorboard", "stdout"]))
            else:
                model = MaskablePPO(
                    "MlpPolicy",
                    vec_env,
                    verbose=1,
                    n_steps=N_STEPS,
                    batch_size=BATCH_SIZE,
                    n_epochs=N_EPOCHS,
                    gamma=GAMMA,
                    learning_rate=LEARNING_RATE,
                    ent_coef=ENT_COEF,
                    device=DEVICE,
                    seed=SEED,
                    policy_kwargs=policy_kwargs,
                )
                # KEY FIX: configure logger immediately
                model.set_logger(configure(log_path, ["tensorboard", "stdout"]))
            model_identity = id(model)
            print(f"[{variation_name}] Phase {phase_idx}: initialized model (id={model_identity})")
        else:
            if model_identity is None:
                model_identity = id(model)
            elif id(model) != model_identity:
                raise RuntimeError(
                    f"[{variation_name}] Model instance changed across phases "
                    f"(expected id={model_identity}, got id={id(model)})."
                )
            print(f"[{variation_name}] Phase {phase_idx}: continuing same model (id={model_identity})")
            model.set_env(vec_env)
            model.set_logger(configure(log_path, ["tensorboard", "stdout"]))

        cont = resumed or phase_idx > 0

        # log matchup info AFTER logger exists
        log_matchup_info(model, LEARNER_ROLE, phase_tiger_ai, phase_goat_opp, phase_mix_env)


        model.learn(
            total_timesteps=phase_steps,
            callback=callback,
            progress_bar=True,
            reset_num_timesteps=not cont,
        )

        total_eps += win_stats_callback.episodes
        total_goat += win_stats_callback.goat_wins
        total_tiger += win_stats_callback.tiger_wins
        total_to += win_stats_callback.max_timeouts
        total_st += win_stats_callback.repeat_timeouts

        vec_env.close()

    if total_eps > 0:
        goat = total_goat / float(total_eps)
        tiger = total_tiger / float(total_eps)
        mto = total_to / float(total_eps)
        rto = total_st / float(total_eps)
    else:
        goat = tiger = mto = rto = 0.0

    print(f"[{variation_name}] Summary:")
    print(f"  Goat {goat:.3f} | Tiger {tiger:.3f} | MaxTO {mto:.3f} | RepeatTO {rto:.3f}")

    # Save final model with phase suffix similar to TB naming
    final_name = f"{ALGO_TAG}_{variation_core}_{variation_name}_p{len(phases)-1}"
    final_path = unique_filename(variation_model_dir, final_name)

    model.save(final_path)
    print(f"Saved final model: {final_path}")

    return {
        "variation": variation_name,
        "episodes": total_eps,
        "goat": goat,
        "tiger": tiger,
        "max_timeout": mto,
        "repeat_stall": rto,
        "final_path": final_path,
    }

# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":
    all_results = []

    print("\n" + "=" * 70)
    print(f"EXPERIMENT (suite): {EXPERIMENT_NAME}")
    print(f"ALGO={ALGO_TAG} | VARIATIONS={len(VARIATIONS)}")
    print("MATCHUPS (per variation):")
    for variation_name, weights in VARIATIONS.items():
        phases = normalize_phases(weights)
        variation_core = resolve_variation_core(phases)
        print(f"  {variation_name}: {variation_core}")
    print("=" * 70)

    for variation_name, weights in VARIATIONS.items():
        res = run_single_variation(variation_name, weights)
        all_results.append(res)

    print("\n=================== VARIATION RESULTS ===================")
    for r in all_results:
        print(
            f"{r['variation']:16s} | "
            f"G {r['goat']:.3f} | "
            f"T {r['tiger']:.3f} | "
            f"MaxTO {r['max_timeout']:.3f} | "
            f"RepeatTO {r['repeat_stall']:.3f} | "
            f"Eps {r['episodes']}"
        )
