# ============================================================
#  Project    : Tigers & Goats – Falcon Branch
#  Module     : Experiment Sweep Runner
#  File       : train_abc.py
#  Version    : mppo_train3.1
#
#  What this file does:
#    Runs an *experiment suite* made of multiple *variations*, where each
#    variation can be either:
#      (A) A single default run (None)
#      (B) A single-phase flat dict (control keys + direct tuning knobs)
#      (C) A multi-phase curriculum (list of flat dict phases) that continues training
#          the *same* model across phases (new TB subdir per phase).
#
#    Each phase creates a fresh SubprocVecEnv, trains for phase_steps, logs
#    windowed outcome metrics, saves periodic checkpoints, then closes the env.
#
#  Key concepts:
#    • EXPERIMENT_NAME / SUITE_TAG:
#         Suite name. Logs + models are grouped under this.
#
#    • CORE (matchup tag):
#         Generated by core_tag(learner_role, opponent_ai, mix=...)
#           - GvNT: Goat vs Normal/Greedy Tiger
#           - GvST: Goat vs Smart Tiger
#           - GvMixT: Goat vs Mixed Tiger (per-reset sampling)
#           - Tv...: Tiger-learner versions (goats become scripted opponent)
#
#    • VARIATIONS:
#         variation_name -> config, where config can be:
#           (A) None
#               → env defaults
#           (B) dict
#               → one phase; supports optional inline keys:
#                   {"timesteps", "opponent_ai", "mix_prob", "checkpoints_per_run", ...knobs...}
#           (C) list[dict]
#               → multi-phase curriculum:
#                   [{"timesteps": ..., "opponent_ai": ..., "mix_prob": ..., ...knobs...}, ...]
#
#    • Tiger mixing (per-reset opponent sampling):
#         If mix_prob is set in a phase, each episode reset samples:
#            TIGER_AI_SMART with probability mix_prob
#            TIGER_AI_GREEDY otherwise
#         Implemented via TigerMixWrapper (Monitor subclass) so it remains
#         pickle-friendly under SubprocVecEnv.
#
#    • Action masking (MaskablePPO requirement):
#         Each worker env is wrapped:
#           BaseEnv -> (Monitor or TigerMixWrapper) -> ActionMasker
#         so MaskablePPO only samples legal actions.
#
#  Outputs (where stuff goes):
#    • Run artifacts (experiment-first):
#         artifacts/{EXPERIMENT_NAME}/
#           ├── meta/         (config_<variation>_<runstamp>.json, git_commit_<variation>_<runstamp>.txt, notes_<variation>_<runstamp>.txt)
#           ├── tb/           (TensorBoard logs by phase)
#           ├── checkpoints/  (phase subfolders with periodic checkpoints)
#           ├── models/       (final_<variation>_<runstamp>_phase_XX.zip + best_<variation>_<runstamp>.zip)
#           ├── eval/
#           └── logs/
#
#    • Resume support:
#         RESUME_MODEL_PATH can be a .zip file OR a directory.
#         If directory, the most recently created .zip is loaded and training
#         continues from it (phase 0 treated as "continued").
#
#  Metrics you should expect in TensorBoard:
#    • 1.episode_stats/*
#         - episode_index
#         - episodes_total_done
#         - overall goat/tiger/timeout/stall rates (cumulative)
#
#    • 2.window_stats/*
#         - windowed goat/tiger/timeout/stall rates over last N episodes
#         - realized opponent fraction (greedy vs smart) in the last N episodes
#           when tiger mode is mixed
#
#    • 3.matchup_info/*
#         - learner_id (0=goat, 1=tiger)
#         - opp_source_id (0=tiger, 1=goat)
#         - opp_family_id (0=greedy/random, 1=smart/model)
#         - is_mixed (0/1)
#         - mix_prob (if mixed)
#
#  Quick Use:
#    1) Choose opponent + role:
#         OPPONENT_AI   = OPP_TIGER_GREEDY
#         # or
#         OPPONENT_AI   = OPP_TIGER_SMART
#         LEARNER_ROLE  = GOAT_LEARNER      # or TIGER_LEARNER
#
#    2) Set identity + compute:
#         EXPERIMENT_NAME = "RobustGoatTraining"
#         TIMESTEPS       = 60_000_000
#         NUM_CPU         = 16
#         DEVICE_MODE     = "gpu"  # uses cuda + larger batch/n_steps
#
#    3) Define variations:
#         VARIATIONS = {
#             "defaultSettings": None,
#             "no_bubble": {"REWARD_BUBBLE_SPACE": 0.0},
#             "no_block": {"REWARD_BLOCK_TIGER": 0.0},
#             "weaker_capture_bias": {"BASE_TIGER_CAPTURE_BIAS": 0.8},
#         }
#
#       Curriculum + mixing example:
#         VARIATIONS = {
#           "greedy_to_smart_mix": [
#             {"timesteps": 10_000_000, "opponent_ai": OPP_TIGER_GREEDY},
#             {"timesteps": 10_000_000, "opponent_ai": OPP_TIGER_SMART},
#             {"timesteps": 30_000_000, "opponent_ai": OPP_TIGER_SMART, "mix_prob": 0.3},
#             {"timesteps": 30_000_000, "opponent_ai": OPP_TIGER_SMART, "mix_prob": 0.5},
#           ]
#         }
#
#    4) Run:
#         python train_abc.py
#
#    5) Watch training:
#         tensorboard --logdir artifacts --port 6006
#
#  Workflow (recommended for ablation studies):
#    1) Establish baseline (single variation, defaults).
#    2) One-at-a-time ablations (set one reward knob to 0.0).
#    3) Group ablations (remove shaping families).
#    4) Magnitude sweeps on selected reward knobs (0.0, 0.25, 0.5, 1.0, 2.0).
#    5) Curriculum runs (greedy -> smart, optional mixing for robustness).
#    6) Evaluate winners with eval_falcon.py across fixed episode counts.
#
# ============================================================



import os
import numpy as np
import torch
import glob
import json
import shutil
import re
import subprocess
from collections import deque
from dataclasses import asdict, dataclass
import random
import sys
from datetime import datetime
from typing import Any

from stable_baselines3.common.vec_env import SubprocVecEnv
from stable_baselines3.common.utils import set_random_seed
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.callbacks import (
    CheckpointCallback,
    BaseCallback,
    CallbackList,
)
from stable_baselines3.common.logger import configure
from sb3_contrib import MaskablePPO
from sb3_contrib.common.wrappers import ActionMasker

from env_tng_abc import (
    TnGEnv as BaseEnv,
    TIGER_AI_GREEDY,
    TIGER_AI_SMART,
    GOAT_AI_RANDOM,
    GOAT_AI_MODEL,
)

GOAT_LEARNER     = "goat"
TIGER_LEARNER    = "tiger"
OPP_TIGER_GREEDY = "tiger_greedy"
OPP_TIGER_SMART  = "tiger_smart"
OPP_GOAT_RANDOM  = "goat_random"
OPP_GOAT_MODEL   = "goat_model"

# ============================================================
#  USER CONFIG — Opponent & Naming
# ============================================================

EXPERIMENT_NAME = "baselineGoatTrainingV3"
LEARNER_ROLE    = GOAT_LEARNER                # GOAT_LEARNER | TIGER_LEARNER
# Unified opponent selector (interpreted by learner role; used when MIX_PROB is None):
#   - GOAT learner  : "tiger_greedy" | "tiger_smart"  (model tiger not yet supported)
#   - TIGER learner : "goat_random"  | "goat_model"
OPPONENT_AI     = OPP_TIGER_SMART
# Mixing control (set to None for fixed opponent):
#   - GOAT learner  : P(smart tiger), else greedy
#   - TIGER learner : P(model goat),  else random
MIX_PROB        = None

ALGO_TAG        = "mppo"
ENV_VER         = "env_5.0"
MODEL_VER       = "mppo_train3.0"
CHECKPOINTS_PER_RUN = 10
RESUME_MODEL_PATH = r"artifacts\baselineGoatTrainingV3\models\final_goat_vs_smart_tiger_50M_20260320_231909_phase_01.zip"
GOAT_MODEL_PATH  = "stable_models\models\Goats\mppo_GvMixT_goat_GT_to_ST_to_mix_p2.zip"  # path to a saved goat model (used when opponent is goat_model)

# ============================================================
#  USER CONFIG — Scale / Hardware
# ============================================================

DEVICE_MODE = "gpu"
DEBUG_MODE  = False                  # True or False
TIMESTEPS   = 2_000_000 if DEBUG_MODE else 20_000_000
NUM_CPU     = 16
SEED        = 42

# ============================================================
#  USER CONFIG — PPO Hyperparameters
# ============================================================

GAMMA         = 0.99
LEARNING_RATE = 3e-4
ENT_COEF      = 0.02

if DEVICE_MODE == "gpu":
    DEVICE     = "cuda"
    N_STEPS    = 4096
    BATCH_SIZE = 256
    N_EPOCHS   = 10
    torch.set_num_threads(1)
elif DEVICE_MODE == "cpu":
    DEVICE     = "cpu"
    N_STEPS    = 512
    BATCH_SIZE = 128
    N_EPOCHS   = 5
else:
    raise ValueError("DEVICE_MODE must be 'gpu' or 'cpu'")

# ============================================================
#  VARIATIONS
# ============================================================

VARIATIONS = {
    "goat_vs_smart_tiger_continue_50M": {
        "timesteps": 50_000_000,
        "opponent_ai": OPP_TIGER_SMART,
        "mix_prob": None,
    },
}



# ============================================================
# Helpers
# ============================================================

CONTROL_KEYS = frozenset({
    "timesteps",
    "opponent_ai",
    "mix_prob",
    "checkpoints_per_run",
    "goat_model_path",
})

LEGACY_VARIATION_KEYS = frozenset({
    "tiger_ai",
    "reward_weights",
})


@dataclass(frozen=True)
class PhaseConfig:
    timesteps: int
    opponent_ai: str
    mix_prob: float | None
    checkpoints_per_run: int
    goat_model_path: str | None
    knobs: dict[str, Any]


def default_phase_config() -> PhaseConfig:
    return PhaseConfig(
        timesteps=TIMESTEPS,
        opponent_ai=OPPONENT_AI,
        mix_prob=MIX_PROB,
        checkpoints_per_run=CHECKPOINTS_PER_RUN,
        goat_model_path=GOAT_MODEL_PATH,
        knobs={},
    )


def _raise_legacy_variation_key_error(key: str, context: str) -> None:
    if key == "tiger_ai":
        raise ValueError(
            f"{context}: 'tiger_ai' is no longer supported. Use 'opponent_ai' instead."
        )
    if key == "reward_weights":
        raise ValueError(
            f"{context}: nested 'reward_weights' is no longer supported. "
            "Put each tuning knob directly in the variation or phase dict."
        )


def normalize_phase_dict(phase_config: dict[str, Any], context: str) -> PhaseConfig:
    if not isinstance(phase_config, dict):
        raise TypeError(f"{context}: expected a dict, got {type(phase_config).__name__}.")

    for legacy_key in LEGACY_VARIATION_KEYS:
        if legacy_key in phase_config:
            _raise_legacy_variation_key_error(legacy_key, context)

    default_phase = default_phase_config()
    knobs = {
        key: value
        for key, value in phase_config.items()
        if key not in CONTROL_KEYS
    }

    return PhaseConfig(
        timesteps=phase_config.get("timesteps", default_phase.timesteps),
        opponent_ai=phase_config.get("opponent_ai", default_phase.opponent_ai),
        mix_prob=phase_config.get("mix_prob", default_phase.mix_prob),
        checkpoints_per_run=phase_config.get("checkpoints_per_run", default_phase.checkpoints_per_run),
        goat_model_path=phase_config.get("goat_model_path", default_phase.goat_model_path),
        knobs=knobs,
    )


def normalize_variation_config(variation_config: Any) -> list[PhaseConfig]:
    if variation_config is None:
        return [default_phase_config()]
    if isinstance(variation_config, dict):
        return [normalize_phase_dict(variation_config, context="variation")]
    if isinstance(variation_config, list):
        return [
            normalize_phase_dict(phase_config, context=f"phase[{idx}]")
            for idx, phase_config in enumerate(variation_config)
        ]
    raise TypeError("Variation config must be None, a dict, or a list of dict phases.")

def core_tag(
    learner_role: str,
    opponent_ai: str,
    mix: bool = False,
    goat_opponent_ai: str | None = None,
) -> str:
    """
    Build a matchup tag:
      - GOAT learner: opponent_ai refers to tiger mode (greedy/smart), mix uses generic MixT.
      - TIGER learner: opponent_ai/goat_opponent_ai refers to goat type (random/model),
        mix marks a mixed-goat opponent.
    """
    learner = "G" if learner_role == GOAT_LEARNER else "T"
    if learner == "T":
        goat_ai = goat_opponent_ai or opponent_ai
        if mix:
            opp = "MixG"
        else:
            opp = "MG" if goat_ai == GOAT_AI_MODEL else "RG"
    else:
        base_opp = "NT" if opponent_ai == TIGER_AI_GREEDY else "ST"
        opp = "MixT" if mix else base_opp
    return f"{learner}v{opp}"


def resolve_opponent_or_exit(learner_role: str, opponent_ai: str) -> tuple[str, str]:
    """
    Map a unified opponent string to (tiger_ai_mode, goat_opponent_ai),
    exiting if the combination is invalid for the current learner role.
    """
    lr = learner_role.lower()
    opp = opponent_ai.lower()

    if lr == GOAT_LEARNER:
        if opp == OPP_TIGER_GREEDY:
            return TIGER_AI_GREEDY, GOAT_AI_RANDOM
        if opp == OPP_TIGER_SMART:
            return TIGER_AI_SMART, GOAT_AI_RANDOM
        print("GOAT learner requires OPPONENT_AI in {tiger_greedy, tiger_smart}")
        sys.exit(1)

    if lr == TIGER_LEARNER:
        if opp == OPP_GOAT_RANDOM:
            return TIGER_AI_SMART, GOAT_AI_RANDOM
        if opp == OPP_GOAT_MODEL:
            return TIGER_AI_SMART, GOAT_AI_MODEL
        print("TIGER learner requires OPPONENT_AI in {goat_random, goat_model}")
        sys.exit(1)

    print("learner_role must be GOAT_LEARNER or TIGER_LEARNER")
    sys.exit(1)


def resolve_variation_core(phases: list[PhaseConfig]) -> str:
    phase_list = phases if phases else [default_phase_config()]
    is_mixed = any(phase.mix_prob is not None for phase in phase_list)

    tiger_modes = set()
    goat_modes = set()
    for phase in phase_list:
        resolved_tiger_ai, resolved_goat_ai = resolve_opponent_or_exit(LEARNER_ROLE, phase.opponent_ai)
        tiger_modes.add(resolved_tiger_ai)
        goat_modes.add(resolved_goat_ai)

    if LEARNER_ROLE == GOAT_LEARNER:
        if is_mixed:
            sample_tiger = next(iter(tiger_modes), TIGER_AI_GREEDY)
            return core_tag(LEARNER_ROLE, sample_tiger, mix=True, goat_opponent_ai=GOAT_AI_RANDOM)
        if len(tiger_modes) == 1:
            only_tiger = next(iter(tiger_modes))
            return core_tag(LEARNER_ROLE, only_tiger, mix=False, goat_opponent_ai=GOAT_AI_RANDOM)
        return "GvNTST"

    if is_mixed:
        sample_goat = next(iter(goat_modes), GOAT_AI_RANDOM)
        return core_tag(LEARNER_ROLE, TIGER_AI_SMART, mix=True, goat_opponent_ai=sample_goat)
    if len(goat_modes) == 1:
        only_goat = next(iter(goat_modes))
        return core_tag(LEARNER_ROLE, TIGER_AI_SMART, mix=False, goat_opponent_ai=only_goat)
    return "TvRGMG"


def make_goat_model_predict_fn(model_path: str | None):
    if not model_path:
        return None

    model = None

    def _predict(obs, mask):
        nonlocal model
        if model is None:
            model = MaskablePPO.load(model_path, device=DEVICE)
        obs_arr = np.asarray(obs)
        if obs_arr.ndim == 1:
            obs_arr = obs_arr.reshape(1, -1)
        mask_arr = None
        if mask is not None:
            mask_arr = np.asarray(mask, dtype=bool)
            if mask_arr.ndim == 1:
                mask_arr = mask_arr.reshape(1, -1)
        action, _ = model.predict(obs_arr, deterministic=True, action_masks=mask_arr)
        if isinstance(action, np.ndarray):
            return int(action[0])
        return int(action)

    return _predict


def warn_if_missing_goat_model_path(goat_opponent_ai: str, model_path: str | None, context: str):
    if goat_opponent_ai == GOAT_AI_MODEL and not model_path:
        print(f"[WARN] {context}: opponent_ai=goat_model but goat_model_path is not set; falling back to random goat.")


def resolve_phase_matchup(phase: PhaseConfig) -> tuple[str, str]:
    return resolve_opponent_or_exit(LEARNER_ROLE, phase.opponent_ai)


def checkpoint_save_freq(phase: PhaseConfig) -> int:
    return max((phase.timesteps // max(phase.checkpoints_per_run, 1)) // NUM_CPU, 1)


def mask_fn(env):
    return env.unwrapped.get_action_mask()

# ============================================================
# Derived config (auto from user settings)
# ============================================================

# Resolve default opponent for env fallbacks
DEFAULT_TIGER_AI_MODE, DEFAULT_GOAT_OPPONENT_AI = resolve_opponent_or_exit(LEARNER_ROLE, OPPONENT_AI)

# ============================================================
# Callbacks
# ============================================================

class WinStatsCallback(BaseCallback):
    """
    Windowed win/timeout stats + optional realized tiger-mode tracking.
    If env includes info["tiger_ai"] at episode end, we will track it.
    """
    def __init__(self, log_every_episodes: int = 200, window_episodes: int = 1_000, verbose: int = 0):
        super().__init__(verbose)
        self.log_every_episodes = log_every_episodes
        self.last_logged_episodes = 0
        self.window_episodes = window_episodes

        # cumulative
        self.episodes = 0
        self.goat_wins = 0
        self.tiger_wins = 0
        self.max_timeouts = 0
        self.repeat_timeouts = 0
        self.window_snapshots = [] # This will stor the most recent 10 snapshots of the windowed stats

        # rolling window of winners
        self.window = deque(maxlen=window_episodes)

        # rolling window of realized opponent modes (optional)
        self.window_tiger_ai = deque(maxlen=window_episodes)  # values: greedy/smart/None
        self.window_goat_ai = deque(maxlen=window_episodes)   # values: random/model/None
        self.reward_component_names = [
            "reward_step_component",
            "reward_near_lock_component",
            "reward_block_component",
            "reward_bubble_component",
            "reward_cluster_component",
            "reward_center_component",
            "reward_goat_eaten_component",
            "reward_repeat_component",
            "reward_terminal_component",
            "reward_decay_mult",
            "reward_total",
        ]
        self.reward_component_windows = {
            name: deque(maxlen=1_000) for name in self.reward_component_names
        }
        self.episode_reward_window = deque(maxlen=window_episodes)
        self.terminal_penalty_windows = {
            "Goat": deque(maxlen=window_episodes),
            "Tiger": deque(maxlen=window_episodes),
            "MaxTimeout": deque(maxlen=window_episodes),
            "RepeatTimeout": deque(maxlen=window_episodes),
        }

    def _on_step(self) -> bool:
        dones = self.locals.get("dones", None)
        infos = self.locals.get("infos", None)

        if infos is not None:
            for info in infos:
                if info is None:
                    continue
                for name in self.reward_component_names:
                    if name in info:
                        self.reward_component_windows[name].append(float(info.get(name, 0.0)))

        if dones is not None and infos is not None:
            for done, info in zip(dones, infos):
                if not done:
                    continue

                winner = info.get("winner", None)

                self.episodes += 1
                if winner == "Goat":
                    self.goat_wins += 1
                elif winner == "Tiger":
                    self.tiger_wins += 1
                elif winner == "MaxTimeout":
                    self.max_timeouts += 1
                elif winner == "RepeatTimeout":
                    self.repeat_timeouts += 1

                self.window.append(winner)

                # optional: realized opponent mode
                # env_tng_abc can set info["tiger_ai"] = TIGER_AI_GREEDY/SMART (or strings)
                self.window_tiger_ai.append(info.get("tiger_ai", None))
                self.window_goat_ai.append(info.get("goat_opponent_ai", info.get("goat_ai", None)))

                episode_info = info.get("episode", None)
                if isinstance(episode_info, dict) and "r" in episode_info:
                    self.episode_reward_window.append(float(episode_info["r"]))

                if winner in self.terminal_penalty_windows:
                    self.terminal_penalty_windows[winner].append(
                        float(info.get("reward_terminal_component", 0.0))
                    )

        # always keep current episode index in logs
        self.logger.record("1.episode_stats (total episodes)/1.episode_index", float(self.episodes))

        if (self.episodes - self.last_logged_episodes) >= self.log_every_episodes and self.episodes > 0:
            total = float(self.episodes)

            self.last_logged_episodes = self.episodes
            # Order of logs (to control TB display grouping)
            self.logger.record("1.episode_stats (total episodes)/2.goat_win_rate", self.goat_wins / total)
            self.logger.record("1.episode_stats (total episodes)/3.tiger_win_rate", self.tiger_wins / total)
            self.logger.record("1.episode_stats (total episodes)/4.max_timeout_rate", self.max_timeouts / total)
            self.logger.record("1.episode_stats (total episodes)/5.repeat_timeout_rate", self.repeat_timeouts / total)

            w = len(self.window)
            if w > 0:
                goat = sum(1 for x in self.window if x == "Goat") / w
                tiger = sum(1 for x in self.window if x == "Tiger") / w
                to = sum(1 for x in self.window if x == "MaxTimeout") / w
                st = sum(1 for x in self.window if x == "RepeatTimeout") / w

                self.logger.record("2.window_stats (per 1000 eps)/1.episodes_tracked", float(w))
                self.logger.record("2.window_stats (per 1000 eps)/2.goat_win_rate", goat)
                self.logger.record("2.window_stats (per 1000 eps)/3.tiger_win_rate", tiger)
                self.logger.record("2.window_stats (per 1000 eps)/4.max_timeout_rate", to)
                self.logger.record("2.window_stats (per 1000 eps)/5.repeat_timeout_rate", st)

                # optional realized opponent distribution in the last-N window
                smart = 0
                greedy = 0
                for v in self.window_tiger_ai:
                    if v == TIGER_AI_SMART or v == "smart" or v == "SMART":
                        smart += 1
                    elif v == TIGER_AI_GREEDY or v == "greedy" or v == "GREEDY":
                        greedy += 1
                denom = smart + greedy
                if denom > 0:
                    self.logger.record("2.window_stats (per 1000 eps)/6.realized_greedy_tiger_frac", greedy / denom)
                    self.logger.record("2.window_stats (per 1000 eps)/7.realized_smart_tiger_frac", smart / denom)

                model = 0
                random_goat = 0
                for v in self.window_goat_ai:
                    if v == GOAT_AI_MODEL or v == "model" or v == "MODEL":
                        model += 1
                    elif v == GOAT_AI_RANDOM or v == "random" or v == "RANDOM":
                        random_goat += 1
                denom = model + random_goat
                if denom > 0:
                    self.logger.record("2.window_stats (per 1000 eps)/8.realized_random_goat_frac", random_goat / denom)
                    self.logger.record("2.window_stats (per 1000 eps)/9.realized_model_goat_frac", model / denom)

            reward_component_labels = {
                "reward_step_component": "1.step_penalty_mean",
                "reward_near_lock_component": "2.near_lock_mean",
                "reward_block_component": "3.block_mean",
                "reward_bubble_component": "4.bubble_mean",
                "reward_cluster_component": "5.cluster_mean",
                "reward_center_component": "6.center_mean",
                "reward_goat_eaten_component": "7.goat_eaten_mean",
                "reward_repeat_component": "8.repeat_mean",
                "reward_terminal_component": "9.terminal_mean",
                "reward_decay_mult": "10.decay_mult_mean",
                "reward_total": "11.total_reward_mean",
            }
            for name, label in reward_component_labels.items():
                values = self.reward_component_windows[name]
                if values:
                    self.logger.record(
                        f"4.reward_components (per 1000 steps)/{label}",
                        sum(values) / float(len(values)),
                    )

            if self.episode_reward_window:
                self.logger.record(
                    "5.episode_reward (per 1000 eps)/1.episode_reward_mean",
                    sum(self.episode_reward_window) / float(len(self.episode_reward_window)),
                )

            terminal_labels = {
                "Goat": "2.goat_terminal_reward_mean",
                "Tiger": "3.tiger_terminal_penalty_mean",
                "MaxTimeout": "4.max_timeout_terminal_penalty_mean",
                "RepeatTimeout": "5.repeat_timeout_terminal_penalty_mean",
            }
            for outcome, label in terminal_labels.items():
                values = self.terminal_penalty_windows[outcome]
                if values:
                    self.logger.record(
                        f"5.episode_reward (per 1000 eps)/{label}",
                        sum(values) / float(len(values)),
                    )

        return True
    

class TigerMixWrapper(Monitor):
    """
    Monitor wrapper that re-samples tiger_ai on every reset using a callable.
    Keeps it top-level (pickle-friendly) and avoids nested class definitions.
    """
    def __init__(self, env, sample_ai_fn):
        super().__init__(env)
        self._sample_ai_fn = sample_ai_fn

    def reset(self, *, seed=None, options=None):
        # Make sure we are modifying the underlying env that actually owns tiger_ai
        ai = self._sample_ai_fn()
        try:
            self.env.tiger_ai = ai
        except Exception:
            pass
        return super().reset(seed=seed, options=options)


class GoatMixWrapper(Monitor):
    """
    Monitor wrapper that re-samples goat_opponent_ai on every reset using a callable.
    Used when the learner is TIGER and we want to mix random/model goats.
    """
    def __init__(self, env, sample_goat_fn):
        super().__init__(env)
        self._sample_goat_fn = sample_goat_fn

    def reset(self, *, seed=None, options=None):
        goat_ai = self._sample_goat_fn()
        # Propagate to underlying env
        try:
            self.env.goat_opponent_ai = goat_ai
        except Exception:
            pass
        return super().reset(seed=seed, options=options)


# ============================================================
# Env factory (supports per-reset mixing)
# ============================================================

def make_env(
    rank: int,
    seed: int,
    knobs: dict[str, Any],
    tiger_ai_mode: str | None = None,
    mix_prob: float | None = None,
    resolved_goat_ai: str | None = None,
    goat_model_path: str | None = None,
):
    def _init():
        def _sample_ai():
            if mix_prob is None:
                return tiger_ai_mode if tiger_ai_mode is not None else DEFAULT_TIGER_AI_MODE
            p = min(max(float(mix_prob), 0.0), 1.0)
            return TIGER_AI_SMART if random.random() < p else TIGER_AI_GREEDY

        def _sample_goat_ai():
            base_goat = resolved_goat_ai if resolved_goat_ai is not None else DEFAULT_GOAT_OPPONENT_AI
            if mix_prob is None or LEARNER_ROLE == GOAT_LEARNER:
                return base_goat
            p = min(max(float(mix_prob), 0.0), 1.0)
            return GOAT_AI_MODEL if random.random() < p else GOAT_AI_RANDOM

        goat_model_predict_fn = make_goat_model_predict_fn(goat_model_path)
        base_env = BaseEnv(
            reward_weights=knobs or None,
            tiger_ai=_sample_ai(),
            learner_role=LEARNER_ROLE,
            goat_opponent_ai=_sample_goat_ai(),
            goat_model_predict_fn=goat_model_predict_fn,
        )

        # If mixing, resample per reset
        if mix_prob is not None and LEARNER_ROLE == GOAT_LEARNER:
            env = TigerMixWrapper(base_env, _sample_ai)
        elif mix_prob is not None and LEARNER_ROLE == TIGER_LEARNER:
            env = GoatMixWrapper(base_env, _sample_goat_ai)
        else:
            env = Monitor(base_env)

        env = ActionMasker(env, mask_fn)
        env.reset(seed=seed + rank)
        return env
    return _init

# ============================================================
# Resume helpers
# ============================================================

def resolve_resume_path(path: str | None) -> str | None:
    if not path:
        return None
    if os.path.isfile(path):
        return path
    if os.path.isdir(path):
        zips = glob.glob(os.path.join(path, "*.zip"))
        if not zips:
            return None
        return max(zips, key=os.path.getctime)
    return None

def unique_filename(directory: str, base_name: str, ext: str = ".zip") -> str:
    full_path = os.path.join(directory, base_name + ext)
    if not os.path.exists(full_path):
        return full_path
    counter = 1
    while True:
        candidate = os.path.join(directory, f"{base_name}_{counter}{ext}")
        if not os.path.exists(candidate):
            return candidate
        counter += 1


def _slugify(text: str) -> str:
    """Filesystem-safe slug for artifact names."""
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "_", (text or "").strip())
    cleaned = re.sub(r"_+", "_", cleaned).strip("._-")
    return cleaned or "run"


def build_run_layout(experiment_name: str, artifacts_root: str = "artifacts") -> dict:
    """
    Build and create experiment-first directory layout:
      artifacts/<experiment>/{meta,tb,checkpoints,models,eval,logs}
    """
    exp_dir = os.path.join(artifacts_root, _slugify(experiment_name))
    os.makedirs(exp_dir, exist_ok=True)

    layout = {
        "experiment_dir": exp_dir,
        "meta_dir": os.path.join(exp_dir, "meta"),
        "tb_dir": os.path.join(exp_dir, "tb"),
        "checkpoints_dir": os.path.join(exp_dir, "checkpoints"),
        "models_dir": os.path.join(exp_dir, "models"),
        "eval_dir": os.path.join(exp_dir, "eval"),
        "logs_dir": os.path.join(exp_dir, "logs"),
    }

    for key in ("experiment_dir", "meta_dir", "tb_dir", "checkpoints_dir", "models_dir", "eval_dir", "logs_dir"):
        os.makedirs(layout[key], exist_ok=True)
    return layout


def _git_commit_or_unknown() -> str:
    """Best-effort git commit hash for reproducibility metadata."""
    try:
        out = subprocess.check_output(["git", "rev-parse", "HEAD"], stderr=subprocess.DEVNULL, text=True).strip()
        return out or "unknown"
    except Exception:
        return "unknown"


def write_run_metadata(
    layout: dict,
    variation_name: str,
    variation_core: str,
    phases: list[PhaseConfig],
    run_stamp: str,
) -> None:
    """Write variation-specific metadata files under meta/."""
    variation_slug = _slugify(variation_name)
    config_payload = {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "run_stamp": run_stamp,
        "experiment_name": EXPERIMENT_NAME,
        "variation_name": variation_name,
        "variation_slug": variation_slug,
        "variation_core": variation_core,
        "algo_tag": ALGO_TAG,
        "env_ver": ENV_VER,
        "model_ver": MODEL_VER,
        "learner_role": LEARNER_ROLE,
        "num_cpu": NUM_CPU,
        "device_mode": DEVICE_MODE,
        "device": DEVICE,
        "seed": SEED,
        "phases": [asdict(phase) for phase in phases],
        "layout": layout,
    }

    config_path = os.path.join(layout["meta_dir"], f"config_{variation_slug}_{run_stamp}.json")
    with open(config_path, "w", encoding="utf-8") as f:
        json.dump(config_payload, f, indent=2)

    commit_path = os.path.join(layout["meta_dir"], f"git_commit_{variation_slug}_{run_stamp}.txt")
    with open(commit_path, "w", encoding="utf-8") as f:
        f.write(_git_commit_or_unknown() + "\n")

    notes_path = os.path.join(layout["meta_dir"], f"notes_{variation_slug}_{run_stamp}.txt")
    if not os.path.exists(notes_path):
        with open(notes_path, "w", encoding="utf-8") as f:
            f.write("")

# ============================================================
# Matchup info logger (scalar)
# ============================================================

def log_matchup_info(model_obj, learner_role, tiger_ai, resolved_goat_ai, mix_prob):
    learner_id = 0.0 if learner_role == GOAT_LEARNER else 1.0
    opp_source_id = 0.0 if learner_role == GOAT_LEARNER else 1.0  # 0=tiger, 1=goat
    if learner_role == GOAT_LEARNER:
        opp_family_id = 1.0 if tiger_ai == TIGER_AI_SMART else 0.0
    else:
        opp_family_id = 1.0 if resolved_goat_ai == GOAT_AI_MODEL else 0.0

    model_obj.logger.record("3.matchup_info/1.learner_id", learner_id)
    model_obj.logger.record("3.matchup_info/2.opp_source_id", opp_source_id)
    model_obj.logger.record("3.matchup_info/3.opp_family_id", opp_family_id)
    model_obj.logger.record("3.matchup_info/4.is_mixed", 0.0 if mix_prob is None else 1.0)
    if mix_prob is not None:
        model_obj.logger.record("3.matchup_info/5.mix_prob", float(mix_prob))
    model_obj.logger.dump(step=model_obj.num_timesteps)


def configure_model_for_phase(
    model: MaskablePPO | None,
    model_identity: int | None,
    vec_env: SubprocVecEnv,
    log_path: str,
    resume_path: str | None,
    variation_name: str,
    phase_idx: int,
    policy_kwargs: dict[str, Any],
) -> tuple[MaskablePPO, int]:
    if model is None:
        if resume_path:
            print(f"[{variation_name}] Loading existing model for continued training:\n  {resume_path}")
            model = MaskablePPO.load(resume_path, env=vec_env, device=DEVICE)
            model.set_env(vec_env)
            model.verbose = 1
        else:
            model = MaskablePPO(
                "MlpPolicy",
                vec_env,
                verbose=1,
                n_steps=N_STEPS,
                batch_size=BATCH_SIZE,
                n_epochs=N_EPOCHS,
                gamma=GAMMA,
                learning_rate=LEARNING_RATE,
                ent_coef=ENT_COEF,
                device=DEVICE,
                seed=SEED,
                policy_kwargs=policy_kwargs,
            )
        model.set_logger(configure(log_path, ["tensorboard", "stdout"]))
        model_identity = id(model)
        print(f"[{variation_name}] Phase {phase_idx}: initialized model (id={model_identity})")
        return model, model_identity

    if model_identity is None:
        model_identity = id(model)
    elif id(model) != model_identity:
        raise RuntimeError(
            f"[{variation_name}] Model instance changed across phases "
            f"(expected id={model_identity}, got id={id(model)})."
        )

    print(f"[{variation_name}] Phase {phase_idx}: continuing same model (id={model_identity})")
    model.set_env(vec_env)
    model.set_logger(configure(log_path, ["tensorboard", "stdout"]))
    return model, model_identity

# ============================================================
# Core: run one variation
# ============================================================

def run_single_variation(variation_name: str, variation_config):
    set_random_seed(SEED)

    phases = normalize_variation_config(variation_config)
    variation_slug = _slugify(variation_name)
    run_stamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    variation_core = resolve_variation_core(phases)
    layout = build_run_layout(EXPERIMENT_NAME, artifacts_root="artifacts")
    write_run_metadata(layout, variation_name, variation_core, phases, run_stamp)

    tb_root = layout["tb_dir"]
    checkpoints_root = layout["checkpoints_dir"]
    models_root = layout["models_dir"]

    print(f"Starting {NUM_CPU} env workers ({variation_core})...")
    print(f"ENV_VER={ENV_VER}, MODEL_VER={MODEL_VER}, TIMESTEPS={TIMESTEPS}")
    print(f"DEVICE_MODE={DEVICE_MODE}, DEVICE={DEVICE}")
    print(f"Artifact root: {layout['experiment_dir']}")
    print("=" * 70)
    print(f"Starting variation: {variation_name}")
    print("=" * 70)

    policy_kwargs = dict(net_arch=[256, 256, 256])

    resume_path = resolve_resume_path(RESUME_MODEL_PATH)
    if RESUME_MODEL_PATH and not resume_path:
        print(f"[{variation_name}] [WARN] RESUME_MODEL_PATH set but no .zip found at: {RESUME_MODEL_PATH}")
    resumed = bool(resume_path)
    model = None
    model_identity = None
    best_phase_score = float("-inf")
    best_phase_path = None
    final_path = None

    total_goat = total_tiger = total_to = total_st = 0
    total_eps = 0

    for phase_idx, phase in enumerate(phases):
        phase_number = phase_idx + 1
        phase_save_freq = checkpoint_save_freq(phase)
        phase_tag = f"{variation_slug}_{run_stamp}_phase_{phase_idx + 1:02d}"
        phase_ckpt_dir = os.path.join(checkpoints_root, phase_tag)
        phase_tb_dir = os.path.join(tb_root, phase_tag)
        os.makedirs(phase_ckpt_dir, exist_ok=True)
        os.makedirs(phase_tb_dir, exist_ok=True)

        phase_tiger_ai, phase_goat_ai = resolve_phase_matchup(phase)

        print(f"Phase {phase_number}: timesteps={phase.timesteps}, opponent_ai={phase.opponent_ai}, mix_prob={phase.mix_prob}")
        warn_if_missing_goat_model_path(
            phase_goat_ai,
            phase.goat_model_path,
            context=f"variation={variation_name} phase={phase_number}",
        )

        env_fns = [
            make_env(
                i,
                seed=SEED,
                knobs=phase.knobs,
                tiger_ai_mode=phase_tiger_ai,
                mix_prob=phase.mix_prob,
                resolved_goat_ai=phase_goat_ai,
                goat_model_path=phase.goat_model_path,
            )
            for i in range(NUM_CPU)
        ]
        vec_env = SubprocVecEnv(env_fns)

        win_stats_callback = WinStatsCallback()

        chk_callback = CheckpointCallback(
            save_freq=phase_save_freq,
            save_path=phase_ckpt_dir,
            name_prefix=f"cp_{ALGO_TAG}_{variation_core}_{variation_slug}_{run_stamp}",
            save_replay_buffer=True,
            save_vecnormalize=True,
        )

        callback = CallbackList([
            chk_callback,  
            win_stats_callback
            ]
        )

        log_path = phase_tb_dir

        model, model_identity = configure_model_for_phase(
            model=model,
            model_identity=model_identity,
            vec_env=vec_env,
            log_path=log_path,
            resume_path=resume_path,
            variation_name=variation_name,
            phase_idx=phase_number,
            policy_kwargs=policy_kwargs,
        )

        cont = resumed or phase_idx > 0

        # log matchup info AFTER logger exists
        log_matchup_info(model, LEARNER_ROLE, phase_tiger_ai, phase_goat_ai, phase.mix_prob)


        model.learn(
            total_timesteps=phase.timesteps,
            callback=callback,
            progress_bar=True,
            reset_num_timesteps=not cont,
        )

        total_eps += win_stats_callback.episodes
        total_goat += win_stats_callback.goat_wins
        total_tiger += win_stats_callback.tiger_wins
        total_to += win_stats_callback.max_timeouts
        total_st += win_stats_callback.repeat_timeouts

        phase_model_name = f"final_{variation_slug}_{run_stamp}_phase_{phase_idx + 1:02d}"
        phase_model_path = unique_filename(models_root, phase_model_name)
        model.save(phase_model_path)
        final_path = phase_model_path

        if win_stats_callback.episodes > 0:
            phase_goat_rate = win_stats_callback.goat_wins / float(win_stats_callback.episodes)
            phase_tiger_rate = win_stats_callback.tiger_wins / float(win_stats_callback.episodes)
        else:
            phase_goat_rate = 0.0
            phase_tiger_rate = 0.0
        phase_score = phase_tiger_rate if LEARNER_ROLE == TIGER_LEARNER else phase_goat_rate
        if phase_score > best_phase_score:
            best_phase_score = phase_score
            best_phase_path = phase_model_path

        vec_env.close()

    if total_eps > 0:
        goat = total_goat / float(total_eps)
        tiger = total_tiger / float(total_eps)
        mto = total_to / float(total_eps)
        rto = total_st / float(total_eps)
    else:
        goat = tiger = mto = rto = 0.0

    print(f"[{variation_name}] Summary:")
    print(f"  Goat {goat:.3f} | Tiger {tiger:.3f} | MaxTO {mto:.3f} | RepeatTO {rto:.3f}")

    if best_phase_path and os.path.exists(best_phase_path):
        best_zip_path = unique_filename(models_root, f"best_{variation_slug}_{run_stamp}")
        shutil.copy2(best_phase_path, best_zip_path)
        print(f"Saved best model: {best_zip_path} (source={os.path.basename(best_phase_path)})")
    if final_path:
        print(f"Saved final model: {final_path}")

    return {
        "variation": variation_name,
        "episodes": total_eps,
        "goat": goat,
        "tiger": tiger,
        "max_timeout": mto,
        "repeat_stall": rto,
        "final_path": final_path,
    }

# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":
    all_results = []

    print("\n" + "=" * 70)
    print(f"EXPERIMENT (suite): {EXPERIMENT_NAME}")
    print(f"ALGO={ALGO_TAG} | VARIATIONS={len(VARIATIONS)}")
    print("MATCHUPS (per variation):")
    for variation_name, variation_config in VARIATIONS.items():
        phases = normalize_variation_config(variation_config)
        variation_core = resolve_variation_core(phases)
        print(f"  {variation_name}: {variation_core}")
    print("=" * 70)

    for variation_name, variation_config in VARIATIONS.items():
        res = run_single_variation(variation_name, variation_config)
        all_results.append(res)

    print("\n=================== VARIATION RESULTS ===================")
    for r in all_results:
        print(
            f"{r['variation']:16s} | "
            f"G {r['goat']:.3f} | "
            f"T {r['tiger']:.3f} | "
            f"MaxTO {r['max_timeout']:.3f} | "
            f"RepeatTO {r['repeat_stall']:.3f} | "
            f"Eps {r['episodes']}"
        )
